---
# Name your file secrets.yml
development: 
  OPENAI_TOKEN: create-openAI-token

test: 
  OPENAI_TOKEN: create-openAI-token

production:
  # - assign DATABASE_URL in production
  OPENAI_TOKEN: create-openAI-token
