---
# Name your file secrets.yml
development: 
  GOOGLE_TOKEN: create-googletranslate-token

test: 
  GOOGLE_TOKEN: create-openAI-token

production:
  # - assign DATABASE_URL in production
  GOOGLE_TOKEN: create-openAI-token
